name: Latest blog post workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Updated readme with the latest jianshu data."
          feed_list: "https://rsshub.app/jianshu/user/f6d5674bfbb4"
          max_post_count: 5
    
#   update-readme-with-wechat-official-account:
#     name: Update this repo's README with latest activity from WeChat official Account
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gautamkrishnar/blog-post-workflow@master
#         with:
#           comment_tag_name: "WECHAT-OFFICIAL-ACCOUNT"
#           commit_message: "Updated readme with the latest weChat official account data."
#           feed_list: "https://rsshub.app/jianshu/user/f6d5674bfbb4"
#           max_post_count: 5
